-- Seed inicial gerado a partir de src/constants/products.ts.
-- Usa category como slug da se??o p?blica para preservar os carross?is atuais.

insert into public.products (
  name,
  slug,
  category,
  description,
  image_url,
  price,
  old_price,
  unit_label,
  unit_info,
  discount_label,
  featured,
  available,
  sort_order
) values
  ('Salada de Frutas', 'salada-de-frutas', 'prontos-processados', null, null, 5.99, null, 'unidade', 'Unidade', null, false, true, 1),
  ('Amendoim Cozinhado PCT', 'amendoim-cozinhado-pct', 'prontos-processados', null, null, 5.99, null, 'pacote', 'Pacote', null, false, true, 2),
  ('Alho Poró Processado', 'alho-poro-processado', 'prontos-processados', null, null, 14.99, null, 'unidade', 'Unidade', null, false, true, 3),
  ('Água de Coco Verde 1L', 'agua-de-coco-verde-1l', 'prontos-processados', null, null, 9.99, null, '1L', '1L', null, false, true, 4),
  ('Arroz de Brócolis UND', 'arroz-de-brocolis-und', 'prontos-processados', null, null, 12.99, null, 'unidade', 'Unidade', null, false, true, 5),
  ('Amendoim Torrado PCT', 'amendoim-torrado-pct', 'prontos-processados', null, null, 5.99, null, 'pacote', 'Pacote', null, false, true, 6),
  ('Abacaxi Fatiado BDI', 'abacaxi-fatiado-bdi', 'prontos-processados', null, null, 8.99, null, 'bandeja', 'Bandeja', null, false, true, 7),
  ('Salada de Verduras', 'salada-de-verduras', 'prontos-processados', null, null, 4.99, null, 'unidade', 'Unidade', null, false, true, 8),
  ('Salada Light UND', 'salada-light-und', 'prontos-processados', null, null, 11.99, null, 'unidade', 'Unidade', null, false, true, 9),
  ('Salada de Frango', 'salada-de-frango', 'prontos-processados', null, null, 14.99, null, 'unidade', 'Unidade', null, false, true, 10),
  ('Mix Folhas', 'mix-folhas', 'prontos-processados', null, null, 9.99, null, 'unidade', 'Unidade', null, false, true, 11),
  ('Mix Espaguete', 'mix-espaguete', 'prontos-processados', null, null, 11.99, null, 'unidade', 'Unidade', null, false, true, 12),
  ('Sunomono UND', 'sunomono-und', 'prontos-processados', null, null, 7.99, null, 'unidade', 'Unidade', null, false, true, 13),
  ('Vinagrete UND', 'vinagrete-und', 'prontos-processados', null, null, 4.99, null, 'unidade', 'Unidade', null, false, true, 14),
  ('Coco Ralado', 'coco-ralado', 'prontos-processados', null, null, 5.99, null, 'unidade', 'Unidade', null, false, true, 15),
  ('Kit Feijão Verde KG', 'kit-feijao-verde-kg', 'prontos-processados', null, null, 24.99, null, 'kg', 'Venda por kg', null, false, true, 16),
  ('Mix Cheiro Verde', 'mix-cheiro-verde', 'prontos-processados', null, null, 24.99, null, 'unidade', 'Unidade', null, false, true, 17),
  ('Sobrecoxa KG - Bom Todo', 'sobrecoxa-kg-bom-todo', 'congelados-proteinas', null, null, 15.99, null, 'kg', 'Venda por kg', null, false, true, 18),
  ('Peito de Frango KG - Bom Todo', 'peito-de-frango-kg-bom-todo', 'congelados-proteinas', null, null, 19.99, null, 'kg', 'Venda por kg', null, false, true, 19),
  ('Pão de Alho 400G - Bom Todo', 'pao-de-alho-400g-bom-todo', 'congelados-proteinas', null, null, 13.99, null, '400g', '400g', null, false, true, 20),
  ('Mini Coxinha de Calabresa com Massa de Macaxeira', 'mini-coxinha-de-calabresa-com-massa-de-macaxeira', 'congelados-proteinas', null, null, 17.99, null, 'pacote', 'Pacote', null, false, true, 21),
  ('Frango Desfiado 400G', 'frango-desfiado-400g', 'congelados-proteinas', null, null, 20.99, null, '400g', '400g', null, false, true, 22),
  ('Filé de Tilápia 500G - Bom Todo', 'file-de-tilapia-500g-bom-todo', 'congelados-proteinas', null, null, 34.99, null, '500g', '500g', null, false, true, 23),
  ('Filé de Peito de Frango - Bom Todo', 'file-de-peito-de-frango-bom-todo', 'congelados-proteinas', null, null, 28.99, null, 'unidade', 'Unidade', null, false, true, 24),
  ('Filé de Merluza 800G - Bom Todo', 'file-de-merluza-800g-bom-todo', 'congelados-proteinas', null, null, 34.99, null, '800g', '800g', null, false, true, 25),
  ('Esfera de Queijo 380G - Dream Fest', 'esfera-de-queijo-380g-dream-fest', 'congelados-proteinas', null, null, 20.99, null, '380g', '380g', null, false, true, 26),
  ('Esfera de Bacalhau 380G - Dream Fest', 'esfera-de-bacalhau-380g-dream-fest', 'congelados-proteinas', null, null, 24.99, null, '380g', '380g', null, false, true, 27),
  ('Croquete Misto 380G - Dream Fest', 'croquete-misto-380g-dream-fest', 'congelados-proteinas', null, null, 20.99, null, '380g', '380g', null, false, true, 28),
  ('Coxinha de Frango 380G - Dream Fest', 'coxinha-de-frango-380g-dream-fest', 'congelados-proteinas', null, null, 18.99, null, '380g', '380g', null, false, true, 29),
  ('Coxa e Sobrecoxa KG - Bom Todo', 'coxa-e-sobrecoxa-kg-bom-todo', 'congelados-proteinas', null, null, 15.99, null, 'kg', 'Venda por kg', null, false, true, 30),
  ('Coxa de Frango - Bom Todo', 'coxa-de-frango-bom-todo', 'congelados-proteinas', null, null, 15.99, null, 'unidade', 'Unidade', null, false, true, 31),
  ('Camarão Embalado 320G - Dream Fest', 'camarao-embalado-320g-dream-fest', 'congelados-proteinas', null, null, 34.99, null, '320g', '320g', null, false, true, 32),
  ('Brócolis Congelado 300G - Bom Todo', 'brocolis-congelado-300g-bom-todo', 'congelados-proteinas', null, null, 7.99, null, '300g', '300g', null, false, true, 33),
  ('Batata Palito 2KG - Bom Todo', 'batata-palito-2kg-bom-todo', 'congelados-proteinas', null, null, 29.99, null, '2kg', '2kg', null, false, true, 34),
  ('Batata Palito 1KG - Bom Todo', 'batata-palito-1kg-bom-todo', 'congelados-proteinas', null, null, 18.99, null, '1kg', '1kg', null, false, true, 35),
  ('Essencial da Semana', 'essencial-da-semana', 'combos', null, null, 49.99, null, 'combo', 'Combo', null, true, true, 36),
  ('Combo Família', 'combo-familia', 'combos', null, null, 99.99, null, 'combo', 'Combo', null, true, true, 37),
  ('Achocolatado Nescau 200G', 'achocolatado-nescau-200g', 'mercearia', null, null, 9.99, null, '200g', '200g', null, false, true, 38),
  ('Açúcar Alegre KG', 'acucar-alegre-kg', 'mercearia', null, null, 4.99, null, 'kg', '1kg', null, false, true, 39),
  ('Açúcar Refinado 1KG', 'acucar-refinado-1kg', 'mercearia', null, null, 8.99, null, '1kg', '1kg', null, false, true, 40),
  ('Arroz Camil Branco 1KG', 'arroz-camil-branco-1kg', 'mercearia', null, null, 7.99, null, '1kg', '1kg', null, false, true, 41),
  ('Arroz Kika Parboilizado 1KG', 'arroz-kika-parboilizado-1kg', 'mercearia', null, null, 6.99, null, '1kg', '1kg', null, false, true, 42),
  ('Aveia em Flocos Quaker 165G', 'aveia-em-flocos-quaker-165g', 'mercearia', null, null, 6.99, null, '165g', '165g', null, false, true, 43),
  ('Aveia Flocos Finos 165G - Quaker', 'aveia-flocos-finos-165g-quaker', 'mercearia', null, null, 6.99, null, '165g', '165g', null, false, true, 44),
  ('Azeitona Fatiada Vale Fértil', 'azeitona-fatiada-vale-fertil', 'mercearia', null, null, 7.99, null, 'unidade', 'Unidade', null, false, true, 45),
  ('Azeitona Sem Caroço Vale Fértil', 'azeitona-sem-caroco-vale-fertil', 'mercearia', null, null, 7.99, null, 'unidade', 'Unidade', null, false, true, 46),
  ('Bananada Brazil com Açaí 230G', 'bananada-brazil-com-acai-230g', 'mercearia', null, null, 17.99, null, '230g', '230g', null, false, true, 47),
  ('Bananada Brazil com Cupuaçu 230G', 'bananada-brazil-com-cupuacu-230g', 'mercearia', null, null, 17.99, null, '230g', '230g', null, false, true, 48),
  ('Bananada Brazil Natural 230G', 'bananada-brazil-natural-230g', 'mercearia', null, null, 17.99, null, '230g', '230g', null, false, true, 49),
  ('Biscoito Cream Cracker Vitarella', 'biscoito-cream-cracker-vitarella', 'mercearia', null, null, 6.99, null, 'pacote', 'Pacote', null, false, true, 50),
  ('Biscoito Maria Leite Vitarella', 'biscoito-maria-leite-vitarella', 'mercearia', null, null, 7.99, null, 'pacote', 'Pacote', null, false, true, 51),
  ('Biscoito Rainha Bom Jesus 300G', 'biscoito-rainha-bom-jesus-300g', 'mercearia', null, null, 6.99, null, '300g', '300g', null, false, true, 52),
  ('Biscoito Suíça Bom Jesus 300G', 'biscoito-suica-bom-jesus-300g', 'mercearia', null, null, 6.99, null, '300g', '300g', null, false, true, 53),
  ('Biscoito Treloso 120G Chocolate', 'biscoito-treloso-120g-chocolate', 'mercearia', null, null, 2.29, null, '120g', '120g', null, false, true, 54),
  ('Biscoito Treloso 120G Morango', 'biscoito-treloso-120g-morango', 'mercearia', null, null, 2.29, null, '120g', '120g', null, false, true, 55),
  ('Biscoito Vitarella Rosquinha Chocolate 350G', 'biscoito-vitarella-rosquinha-chocolate-350g', 'mercearia', null, null, 6.99, null, '350g', '350g', null, false, true, 56),
  ('Biscoito Vitarella Rosquinha Coco 350G', 'biscoito-vitarella-rosquinha-coco-350g', 'mercearia', null, null, 6.99, null, '350g', '350g', null, false, true, 57),
  ('Biscoito Vitarella Rosquinha Leite 350G', 'biscoito-vitarella-rosquinha-leite-350g', 'mercearia', null, null, 6.99, null, '350g', '350g', null, false, true, 58),
  ('Café São Brás Família 250G', 'cafe-sao-bras-familia-250g', 'mercearia', null, null, 18.99, null, '250g', '250g', null, false, true, 59),
  ('Café Solúvel Nescafé 50G', 'cafe-soluvel-nescafe-50g', 'mercearia', null, null, 6.99, null, '50g', '50g', null, false, true, 60),
  ('Café Solúvel Santa Clara 40G', 'cafe-soluvel-santa-clara-40g', 'mercearia', null, null, 6.49, null, '40g', '40g', null, false, true, 61),
  ('Canela em Pó 100% Pura 35G', 'canela-em-po-100-pura-35g', 'mercearia', null, null, 6.99, null, '35g', '35g', null, false, true, 62),
  ('Catchup Tambaú PET 830G', 'catchup-tambau-pet-830g', 'mercearia', null, null, 11.99, null, '830g', '830g', null, false, true, 63),
  ('Creme de Leite Betânia 200G', 'creme-de-leite-betania-200g', 'mercearia', null, null, 4.99, null, '200g', '200g', null, false, true, 64),
  ('Creme de Leite Italac 200G', 'creme-de-leite-italac-200g', 'mercearia', null, null, 4.99, null, '200g', '200g', null, false, true, 65),
  ('Creme de Leite Piracanjuba 200G', 'creme-de-leite-piracanjuba-200g', 'mercearia', null, null, 4.99, null, '200g', '200g', null, false, true, 66),
  ('Farofa Seridoense 300G', 'farofa-seridoense-300g', 'mercearia', null, null, 14.99, null, '300g', '300g', null, false, true, 67),
  ('Feijão Camil Carioca', 'feijao-camil-carioca', 'mercearia', null, null, 11.99, null, 'pacote', 'Pacote', null, false, true, 68),
  ('Feijão Camil Preto 1KG', 'feijao-camil-preto-1kg', 'mercearia', null, null, 9.99, null, '1kg', '1kg', null, false, true, 69),
  ('Fermento Qualimax 100G', 'fermento-qualimax-100g', 'mercearia', null, null, 7.99, null, '100g', '100g', null, false, true, 70),
  ('Fermento Royal 100G', 'fermento-royal-100g', 'mercearia', null, null, 8.99, null, '100g', '100g', null, false, true, 71),
  ('Flocão Coringa 500G', 'flocao-coringa-500g', 'mercearia', null, null, 3.99, null, '500g', '500g', null, false, true, 72),
  ('Flocão Novomilho 500G', 'flocao-novomilho-500g', 'mercearia', null, null, 2.49, null, '500g', '500g', null, false, true, 73),
  ('Flocão São Brás Não Transgênico 500G', 'flocao-sao-bras-nao-transgenico-500g', 'mercearia', null, null, 4.99, null, '500g', '500g', null, false, true, 74),
  ('Gelatina Diet Maracujá', 'gelatina-diet-maracuja', 'mercearia', null, null, 5.99, null, 'unidade', 'Unidade', null, false, true, 75),
  ('Gelatina Diet Morango', 'gelatina-diet-morango', 'mercearia', null, null, 5.99, null, 'unidade', 'Unidade', null, false, true, 76),
  ('Ketchup Heinz 567G', 'ketchup-heinz-567g', 'mercearia', null, null, 14.99, null, '567g', '567g', null, false, true, 77),
  ('Lámen de Carne Vitarella', 'lamen-de-carne-vitarella', 'mercearia', null, null, 1.99, null, 'unidade', 'Unidade', null, false, true, 78),
  ('Lámen de Galinha Vitarella', 'lamen-de-galinha-vitarella', 'mercearia', null, null, 1.99, null, 'unidade', 'Unidade', null, false, true, 79),
  ('Lámen Galinha Caipira Vitarella', 'lamen-galinha-caipira-vitarella', 'mercearia', null, null, 1.99, null, 'unidade', 'Unidade', null, false, true, 80),
  ('Lasanha Pré-Cozida 200G - Galo', 'lasanha-pre-cozida-200g-galo', 'mercearia', null, null, 9.99, null, '200g', '200g', null, false, true, 81),
  ('Leite Condensado Semidesnatado Betânia', 'leite-condensado-semidesnatado-betania', 'mercearia', null, null, 7.99, null, 'unidade', 'Unidade', null, false, true, 82),
  ('Leite Desnatado Betânia 1L', 'leite-desnatado-betania-1l', 'mercearia', null, null, 7.99, null, '1L', '1L', null, false, true, 83),
  ('Leite em Pó Integral Itambé 200G', 'leite-em-po-integral-itambe-200g', 'mercearia', null, null, 9.99, null, '200g', '200g', null, false, true, 84),
  ('Leite Ninho em Pó Lata Integral 380G', 'leite-ninho-em-po-lata-integral-380g', 'mercearia', null, null, 21.99, null, '380g', '380g', null, false, true, 85),
  ('Leite Ninho em Pó Sachê Integral 750G', 'leite-ninho-em-po-sache-integral-750g', 'mercearia', null, null, 41.99, null, '750g', '750g', null, false, true, 86),
  ('Leite UHT Zero Lactose Betânia 1L', 'leite-uht-zero-lactose-betania-1l', 'mercearia', null, null, 8.99, null, '1L', '1L', null, false, true, 87),
  ('Macarrão Lasanha Vitarella Sêmola 500G', 'macarrao-lasanha-vitarella-semola-500g', 'mercearia', null, null, 8.99, null, '500g', '500g', null, false, true, 88),
  ('Macarrão Vitarella Espaguete Fino', 'macarrao-vitarella-espaguete-fino', 'mercearia', null, null, 3.99, null, 'pacote', 'Pacote', null, false, true, 89),
  ('Macarrão Vitarella Sêmola Parafuso Speciale 500G', 'macarrao-vitarella-semola-parafuso-speciale-500g', 'mercearia', null, null, 4.99, null, '500g', '500g', null, false, true, 90),
  ('Macarrão Vitarella Spec Ninho Sêmola 500G', 'macarrao-vitarella-spec-ninho-semola-500g', 'mercearia', null, null, 6.99, null, '500g', '500g', null, false, true, 91),
  ('Maionese Heinz 390G', 'maionese-heinz-390g', 'mercearia', null, null, 16.99, null, '390g', '390g', null, false, true, 92),
  ('Maionese Quero 200G Sachê', 'maionese-quero-200g-sache', 'mercearia', null, null, 3.99, null, '200g', '200g', null, false, true, 93),
  ('Milho para Pipoca 400G', 'milho-para-pipoca-400g', 'mercearia', null, null, 5.99, null, '400g', '400g', null, false, true, 94),
  ('Molho Barbecue Sadia 380G', 'molho-barbecue-sadia-380g', 'mercearia', null, null, 11.99, null, '380g', '380g', null, false, true, 95),
  ('Molho de Alho Gota Regina 150ML', 'molho-de-alho-gota-regina-150ml', 'mercearia', null, null, 3.99, null, '150ml', '150ml', null, false, true, 96),
  ('Molho de Pimenta ao Leite 150ML', 'molho-de-pimenta-ao-leite-150ml', 'mercearia', null, null, 3.99, null, '150ml', '150ml', null, false, true, 97),
  ('Molho de Pimenta Regina 150ML', 'molho-de-pimenta-regina-150ml', 'mercearia', null, null, 3.99, null, '150ml', '150ml', null, false, true, 98),
  ('Molho de Tomate Quero 240G', 'molho-de-tomate-quero-240g', 'mercearia', null, null, 3.99, null, '240g', '240g', null, false, true, 99),
  ('Molho de Tomate Tradicional Heinz 240G', 'molho-de-tomate-tradicional-heinz-240g', 'mercearia', null, null, 4.99, null, '240g', '240g', null, false, true, 100),
  ('Molho Inglês Regina 150ML', 'molho-ingles-regina-150ml', 'mercearia', null, null, 3.99, null, '150ml', '150ml', null, false, true, 101),
  ('Molho Shoyu Regina 150ML', 'molho-shoyu-regina-150ml', 'mercearia', null, null, 3.99, null, '150ml', '150ml', null, false, true, 102),
  ('Quero Ervilha 170G', 'quero-ervilha-170g', 'mercearia', null, null, 4.99, null, '170g', '170g', null, false, true, 103),
  ('Quero Ketchup 400G', 'quero-ketchup-400g', 'mercearia', null, null, 8.99, null, '400g', '400g', null, false, true, 104),
  ('Quero Milho e Ervilha 170G', 'quero-milho-e-ervilha-170g', 'mercearia', null, null, 4.99, null, '170g', '170g', null, false, true, 105),
  ('Sal Grosso 1KG', 'sal-grosso-1kg', 'mercearia', null, null, 2.49, null, '1kg', '1kg', null, false, true, 106),
  ('Sal Moído KG', 'sal-moido-kg', 'mercearia', null, null, 2.49, null, 'kg', '1kg', null, false, true, 107),
  ('Sal Parrilha Defumado 450G - Maker', 'sal-parrilha-defumado-450g-maker', 'mercearia', null, null, 21.99, null, '450g', '450g', null, false, true, 108),
  ('Sal Parrilha Ervas Finas 450G - Maker', 'sal-parrilha-ervas-finas-450g-maker', 'mercearia', null, null, 21.99, null, '450g', '450g', null, false, true, 109),
  ('Sal Parrilha Pimenta 450G - Maker', 'sal-parrilha-pimenta-450g-maker', 'mercearia', null, null, 21.99, null, '450g', '450g', null, false, true, 110),
  ('Sal Parrilha Tradicional 450G - Maker', 'sal-parrilha-tradicional-450g-maker', 'mercearia', null, null, 21.99, null, '450g', '450g', null, false, true, 111),
  ('Sardinha com Molho de Tomate 160G - 88', 'sardinha-com-molho-de-tomate-160g-88', 'mercearia', null, null, 7.99, null, '160g', '160g', null, false, true, 112),
  ('Sardinha Óleo 160G - 88', 'sardinha-oleo-160g-88', 'mercearia', null, null, 7.99, null, '160g', '160g', null, false, true, 113),
  ('Torrada Vitarella Integral', 'torrada-vitarella-integral', 'mercearia', null, null, 5.99, null, 'pacote', 'Pacote', null, false, true, 114),
  ('Torrada Vitarella Multigrãos', 'torrada-vitarella-multigraos', 'mercearia', null, null, 5.99, null, 'pacote', 'Pacote', null, false, true, 115),
  ('Vela Nº 8 - Vidaluz', 'vela-n-8-vidaluz', 'mercearia', null, null, 7.99, null, 'unidade', 'Unidade', null, false, true, 116),
  ('Vinagre de Maçã Orgânico 500ML', 'vinagre-de-maca-organico-500ml', 'mercearia', null, null, 39.99, null, '500ml', '500ml', null, false, true, 117),
  ('Vinagre Minhoto Álcool 250ML', 'vinagre-minhoto-alcool-250ml', 'mercearia', null, null, 3.49, null, '250ml', '250ml', null, false, true, 118),
  ('Tomate Cereja 180G', 'tomate-cereja-180g', 'legumes-verduras', null, null, 7.99, null, '180g', '180g', null, false, true, 119),
  ('Tomate KG', 'tomate-kg', 'legumes-verduras', null, null, 12.99, null, 'kg', 'Venda por kg', null, false, true, 120),
  ('Repolho Roxo 500G', 'repolho-roxo-500g', 'legumes-verduras', null, null, 4.99, null, '500g', '500g', null, false, true, 121),
  ('Repolho Branco 1KG', 'repolho-branco-1kg', 'legumes-verduras', null, null, 6.99, null, '1kg', '1kg', null, false, true, 122),
  ('Pimentão Vermelho KG', 'pimentao-vermelho-kg', 'legumes-verduras', null, null, 24.99, null, 'kg', 'Venda por kg', null, false, true, 123),
  ('Pimentão Amarelo KG', 'pimentao-amarelo-kg', 'legumes-verduras', null, null, 24.99, null, 'kg', 'Venda por kg', null, false, true, 124),
  ('Pimentão UND', 'pimentao-und', 'legumes-verduras', null, null, 2.49, null, 'unidade', 'Unidade', null, false, true, 125),
  ('Pimenta de Cheiro PCT', 'pimenta-de-cheiro-pct', 'legumes-verduras', null, null, 3.99, null, 'pacote', 'Pacote', null, false, true, 126),
  ('Pepino Japonês 500G', 'pepino-japones-500g', 'legumes-verduras', null, null, 3.99, null, '500g', '500g', null, false, true, 127),
  ('Pepino 500G', 'pepino-500g', 'legumes-verduras', null, null, 2.99, null, '500g', '500g', null, false, true, 128),
  ('Milho 5 Unidades Pacote', 'milho-5-unidades-pacote', 'legumes-verduras', null, null, 7.99, null, 'unidade', '5 unidades', null, false, true, 129),
  ('Macaxeira Descascada KG', 'macaxeira-descascada-kg', 'legumes-verduras', null, null, 6.99, null, 'kg', 'Venda por kg', null, false, true, 130),
  ('Macaxeira com Casca KG', 'macaxeira-com-casca-kg', 'legumes-verduras', null, null, 4.99, null, 'kg', 'Venda por kg', null, false, true, 131),
  ('Jerimum de Leite KG', 'jerimum-de-leite-kg', 'legumes-verduras', null, null, 5.99, null, 'kg', 'Venda por kg', null, false, true, 132),
  ('Jerimum Caboclo KG', 'jerimum-caboclo-kg', 'legumes-verduras', null, null, 7.99, null, 'kg', 'Venda por kg', null, false, true, 133),
  ('Inhame KG', 'inhame-kg', 'legumes-verduras', null, null, 14.99, null, 'kg', 'Venda por kg', null, false, true, 134),
  ('Feijão Verde 500G', 'feijao-verde-500g', 'legumes-verduras', null, null, 12.50, null, '500g', '500g', null, false, true, 135),
  ('Chuchu UND', 'chuchu-und', 'legumes-verduras', null, null, 3.99, null, 'unidade', 'Unidade', null, false, true, 136),
  ('Cenoura 1KG', 'cenoura-1kg', 'legumes-verduras', null, null, 10.99, null, '1kg', '1kg', null, false, true, 137),
  ('Cebola Roxa 500G', 'cebola-roxa-500g', 'legumes-verduras', null, null, 3.99, null, '500g', '500g', null, false, true, 138),
  ('Cebola 1KG', 'cebola-1kg', 'legumes-verduras', null, null, 8.99, null, '1kg', '1kg', null, false, true, 139),
  ('Cará KG', 'cara-kg', 'legumes-verduras', null, null, 8.99, null, 'kg', 'Venda por kg', null, false, true, 140),
  ('Beterraba 500G', 'beterraba-500g', 'legumes-verduras', null, null, 4.99, null, '500g', '500g', null, false, true, 141),
  ('Berinjela 500G', 'berinjela-500g', 'legumes-verduras', null, null, 2.99, null, '500g', '500g', null, false, true, 142),
  ('Batata Inglesa 1KG', 'batata-inglesa-1kg', 'legumes-verduras', null, null, 12.99, null, '1kg', '1kg', null, false, true, 143),
  ('Batata Doce KG', 'batata-doce-kg', 'legumes-verduras', null, null, 5.99, null, 'kg', 'Venda por kg', null, false, true, 144),
  ('Alho Pacote 500G', 'alho-pacote-500g', 'legumes-verduras', null, null, 19.99, null, '500g', '500g', null, false, true, 145),
  ('Alho Descascado Congelado 300G - Bom Todo', 'alho-descascado-congelado-300g-bom-todo', 'legumes-verduras', null, null, 9.99, null, '300g', '300g', null, false, true, 146),
  ('Alho Branco/Roxo UND', 'alho-brancoroxo-und', 'legumes-verduras', null, null, 3.99, null, 'unidade', 'Unidade', null, false, true, 147),
  ('Abobrinha 500G', 'abobrinha-500g', 'legumes-verduras', null, null, 3.99, null, '500g', '500g', null, false, true, 148),
  ('Uva Vitória Sem Sementes 500G', 'uva-vitoria-sem-sementes-500g', 'frutas', null, null, 7.99, null, '500g', '500g', null, false, true, 149),
  ('Uva Thompson 500G Sem Semente', 'uva-thompson-500g-sem-semente', 'frutas', null, null, 14.99, null, '500g', '500g', null, false, true, 150),
  ('Uva Red Isis 500G Sem Semente', 'uva-red-isis-500g-sem-semente', 'frutas', null, null, 9.99, null, '500g', '500g', null, false, true, 151),
  ('Uva Jubileu/Núbia 500G', 'uva-jubileunubia-500g', 'frutas', null, null, 8.99, null, '500g', '500g', null, false, true, 152),
  ('Uva Itália 500G', 'uva-italia-500g', 'frutas', null, null, 7.99, null, '500g', '500g', null, false, true, 153),
  ('Tangerina Importada KG', 'tangerina-importada-kg', 'frutas', null, null, 19.99, null, 'kg', 'Venda por kg', null, false, true, 154),
  ('Pitaya KG', 'pitaya-kg', 'frutas', null, null, 29.99, null, 'kg', 'Venda por kg', null, false, true, 155),
  ('Pêra Portuguesa 500G', 'pera-portuguesa-500g', 'frutas', null, null, 10.99, null, '500g', '500g', null, false, true, 156),
  ('Pêra Argentina 500G', 'pera-argentina-500g', 'frutas', null, null, 11.99, null, '500g', '500g', null, false, true, 157),
  ('Morango Premium 250G', 'morango-premium-250g', 'frutas', null, null, 16.99, null, '250g', '250g', null, false, true, 158),
  ('Melão Rei KG', 'melao-rei-kg', 'frutas', null, null, 15.99, null, 'kg', 'Venda por kg', null, false, true, 159),
  ('Melão Japonês KG', 'melao-japones-kg', 'frutas', null, null, 5.99, null, 'kg', 'Venda por kg', null, false, true, 160),
  ('Melão Espanhol KG', 'melao-espanhol-kg', 'frutas', null, null, 5.99, null, 'kg', 'Venda por kg', null, false, true, 161),
  ('Melancia Baby KG', 'melancia-baby-kg', 'frutas', null, null, 5.99, null, 'kg', 'Venda por kg', null, false, true, 162),
  ('Melancia KG', 'melancia-kg', 'frutas', null, null, 3.49, null, 'kg', 'Venda por kg', null, false, true, 163),
  ('Maracujá KG', 'maracuja-kg', 'frutas', null, null, 7.99, null, 'kg', 'Venda por kg', null, false, true, 164),
  ('Manga Tommy KG', 'manga-tommy-kg', 'frutas', null, null, 6.99, null, 'kg', 'Venda por kg', null, false, true, 165),
  ('Manga Rosa KG', 'manga-rosa-kg', 'frutas', null, null, 7.99, null, 'kg', 'Venda por kg', null, false, true, 166),
  ('Manga Palmer KG', 'manga-palmer-kg', 'frutas', null, null, 6.99, null, 'kg', 'Venda por kg', null, false, true, 167),
  ('Mamão Havaí KG', 'mamao-havai-kg', 'frutas', null, null, 4.99, null, 'kg', 'Venda por kg', null, false, true, 168),
  ('Mamão Formosa Gold KG', 'mamao-formosa-gold-kg', 'frutas', null, null, 7.99, null, 'kg', 'Venda por kg', null, false, true, 169),
  ('Mamão Formosa KG', 'mamao-formosa-kg', 'frutas', null, null, 4.99, null, 'kg', 'Venda por kg', null, false, true, 170),
  ('Maçã Verde KG', 'maca-verde-kg', 'frutas', null, null, 16.99, null, 'kg', 'Venda por kg', null, false, true, 171),
  ('Maçã Red KG', 'maca-red-kg', 'frutas', null, null, 16.99, null, 'kg', 'Venda por kg', null, false, true, 172),
  ('Maçã Nacional KG', 'maca-nacional-kg', 'frutas', null, null, 14.99, null, 'kg', 'Venda por kg', null, false, true, 173),
  ('Maçã Fuji KG', 'maca-fuji-kg', 'frutas', null, null, 16.99, null, 'kg', 'Venda por kg', null, false, true, 174),
  ('Limão Siciliano KG', 'limao-siciliano-kg', 'frutas', null, null, 17.99, null, 'kg', 'Venda por kg', null, false, true, 175),
  ('Limão KG', 'limao-kg', 'frutas', null, null, 5.99, null, 'kg', 'Venda por kg', null, false, true, 176),
  ('Laranja Pêra 18KG', 'laranja-pera-18kg', 'frutas', null, null, 59.99, null, 'Saco 18kg', 'Saco 18kg', null, false, true, 177),
  ('Laranja Pêra KG', 'laranja-pera-kg', 'frutas', null, null, 4.49, null, 'kg', 'Venda por kg', null, false, true, 178),
  ('Laranja Navelina KG', 'laranja-navelina-kg', 'frutas', null, null, 14.99, null, 'kg', 'Venda por kg', null, false, true, 179),
  ('Laranja Mimo do Céu KG', 'laranja-mimo-do-ceu-kg', 'frutas', null, null, 8.99, null, 'kg', 'Venda por kg', null, false, true, 180),
  ('Kiwi 500G', 'kiwi-500g', 'frutas', null, null, 17.99, null, '500g', '500g', null, false, true, 181),
  ('Goiaba 1KG', 'goiaba-1kg', 'frutas', null, null, 6.99, null, '1kg', '1kg', null, false, true, 182),
  ('Coco Verde Processado Unidade', 'coco-verde-processado-unidade', 'frutas', null, null, 3.99, null, 'unidade', 'Unidade', null, false, true, 183),
  ('Coco Seco Inteiro', 'coco-seco-inteiro', 'frutas', null, null, 4.99, null, 'unidade', 'Unidade', null, false, true, 184),
  ('Caqui KG', 'caqui-kg', 'frutas', null, null, 34.99, null, 'kg', 'Venda por kg', null, false, true, 185),
  ('Caju Bandeja com 8 Unidades', 'caju-bandeja-com-8-unidades', 'frutas', null, null, 14.99, null, 'unidade', '8 unidades', null, false, true, 186),
  ('Banana Prata KG', 'banana-prata-kg', 'frutas', null, null, 6.99, null, 'kg', 'Venda por kg', null, false, true, 187),
  ('Banana Pacovan KG', 'banana-pacovan-kg', 'frutas', null, null, 5.99, null, 'kg', 'Venda por kg', null, false, true, 188),
  ('Banana Maçã KG', 'banana-maca-kg', 'frutas', null, null, 8.99, null, 'kg', 'Venda por kg', null, false, true, 189),
  ('Banana de Cozinhar KG', 'banana-de-cozinhar-kg', 'frutas', null, null, 9.99, null, 'kg', 'Venda por kg', null, false, true, 190),
  ('Ameixa Fresca 500G', 'ameixa-fresca-500g', 'frutas', null, null, 7.99, null, '500g', '500g', null, false, true, 191),
  ('Acerola KG', 'acerola-kg', 'frutas', null, null, 14.99, null, 'kg', 'Venda por kg', null, false, true, 192),
  ('Abacaxi Unidade', 'abacaxi-unidade', 'frutas', null, null, 7.99, null, 'unidade', 'Unidade', null, false, true, 193),
  ('Abacate KG', 'abacate-kg', 'frutas', null, null, 7.99, null, 'kg', 'Venda por kg', null, false, true, 194),
  ('Acelga KG', 'acelga-kg', 'folhas-temperos', null, null, 9.99, null, 'kg', 'Venda por kg', null, false, true, 195),
  ('Alecrim', 'alecrim', 'folhas-temperos', null, null, 2.99, null, 'unidade', 'Unidade', null, false, true, 196),
  ('Alface Americana', 'alface-americana', 'folhas-temperos', null, null, 3.99, null, 'unidade', 'Unidade', null, false, true, 197),
  ('Alface Crespa', 'alface-crespa', 'folhas-temperos', null, null, 3.99, null, 'unidade', 'Unidade', null, false, true, 198),
  ('Alface Lisa', 'alface-lisa', 'folhas-temperos', null, null, 3.99, null, 'unidade', 'Unidade', null, false, true, 199),
  ('Alface Roxo/Francês', 'alface-roxofrances', 'folhas-temperos', null, null, 3.99, null, 'unidade', 'Unidade', null, false, true, 200),
  ('Alho Poró', 'alho-poro', 'folhas-temperos', null, null, 9.99, null, 'unidade', 'Unidade', null, false, true, 201),
  ('Brócolis UND', 'brocolis-und', 'folhas-temperos', null, null, 13.99, null, 'unidade', 'Unidade', null, false, true, 202),
  ('Cebolinha', 'cebolinha', 'folhas-temperos', null, null, 2.99, null, 'unidade', 'Unidade', null, false, true, 203),
  ('Coentro', 'coentro', 'folhas-temperos', null, null, 3.99, null, 'unidade', 'Unidade', null, false, true, 204),
  ('Couve Flor UND', 'couve-flor-und', 'folhas-temperos', null, null, 21.99, null, 'unidade', 'Unidade', null, false, true, 205),
  ('Couve Folha', 'couve-folha', 'folhas-temperos', null, null, 2.99, null, 'unidade', 'Unidade', null, false, true, 206),
  ('Espinafre', 'espinafre', 'folhas-temperos', null, null, 2.99, null, 'unidade', 'Unidade', null, false, true, 207),
  ('Gengibre 250G', 'gengibre-250g', 'folhas-temperos', null, null, 5.99, null, '250g', '250g', null, false, true, 208),
  ('Hortelã', 'hortela', 'folhas-temperos', null, null, 2.99, null, 'unidade', 'Unidade', null, false, true, 209),
  ('Jiló Bandeja 350G', 'jilo-bandeja-350g', 'folhas-temperos', null, null, 4.99, null, '350g', '350g', null, false, true, 210),
  ('Manjericão', 'manjericao', 'folhas-temperos', null, null, 2.99, null, 'unidade', 'Unidade', null, false, true, 211),
  ('Maxixe Bandeja', 'maxixe-bandeja', 'folhas-temperos', null, null, 4.99, null, 'bandeja', 'Bandeja', null, false, true, 212),
  ('Quiabo Bandeja', 'quiabo-bandeja', 'folhas-temperos', null, null, 4.99, null, 'bandeja', 'Bandeja', null, false, true, 213),
  ('Rúcula', 'rucula', 'folhas-temperos', null, null, 2.99, null, 'unidade', 'Unidade', null, false, true, 214),
  ('Salsa', 'salsa', 'folhas-temperos', null, null, 2.99, null, 'unidade', 'Unidade', null, false, true, 215),
  ('Vagem 250G', 'vagem-250g', 'folhas-temperos', null, null, 15.99, null, '250g', '250g', null, false, true, 216),
  ('Creme de Açaí Fruta Plus 900ML', 'creme-de-acai-fruta-plus-900ml', 'polpas-cremes', null, null, 49.99, null, '900ml', '900ml', null, false, true, 217),
  ('Creme de Cajá Prime 1L - Canaã', 'creme-de-caja-prime-1l-canaa', 'polpas-cremes', null, null, 19.99, null, '1L', '1L', null, false, true, 218),
  ('Creme de Graviola Prime 1L - Canaã', 'creme-de-graviola-prime-1l-canaa', 'polpas-cremes', null, null, 19.99, null, '1L', '1L', null, false, true, 219),
  ('Creme de Morango Prime 1L - Canaã', 'creme-de-morango-prime-1l-canaa', 'polpas-cremes', null, null, 19.99, null, '1L', '1L', null, false, true, 220),
  ('Frutas Vermelhas Congeladas 1KG - Canaã', 'frutas-vermelhas-congeladas-1kg-canaa', 'polpas-cremes', null, null, 39.99, null, '1kg', '1kg', null, false, true, 221),
  ('Morango Congelado Canaã 1KG', 'morango-congelado-canaa-1kg', 'polpas-cremes', null, null, 21.99, null, '1kg', '1kg', null, false, true, 222),
  ('Polpa de Abacaxi Canaã 1KG', 'polpa-de-abacaxi-canaa-1kg', 'polpas-cremes', null, null, 10.99, null, '1kg', '1kg', null, false, true, 223),
  ('Polpa de Açaí Canaã 1KG', 'polpa-de-acai-canaa-1kg', 'polpas-cremes', null, null, 27.99, null, '1kg', '1kg', null, false, true, 224),
  ('Polpa de Acerola Canaã 1KG', 'polpa-de-acerola-canaa-1kg', 'polpas-cremes', null, null, 12.99, null, '1kg', '1kg', null, false, true, 225),
  ('Polpa de Cajá Canaã 1KG', 'polpa-de-caja-canaa-1kg', 'polpas-cremes', null, null, 17.99, null, '1kg', '1kg', null, false, true, 226),
  ('Polpa de Caju Canaã 1KG', 'polpa-de-caju-canaa-1kg', 'polpas-cremes', null, null, 9.99, null, '1kg', '1kg', null, false, true, 227),
  ('Polpa de Goiaba Canaã 1KG', 'polpa-de-goiaba-canaa-1kg', 'polpas-cremes', null, null, 9.99, null, '1kg', '1kg', null, false, true, 228),
  ('Polpa de Graviola Canaã 1KG', 'polpa-de-graviola-canaa-1kg', 'polpas-cremes', null, null, 19.99, null, '1kg', '1kg', null, false, true, 229),
  ('Polpa de Manga Canaã 1KG', 'polpa-de-manga-canaa-1kg', 'polpas-cremes', null, null, 9.99, null, '1kg', '1kg', null, false, true, 230),
  ('Polpa de Maracujá Canaã 1KG', 'polpa-de-maracuja-canaa-1kg', 'polpas-cremes', null, null, 23.99, null, '1kg', '1kg', null, false, true, 231),
  ('Polpa de Morango Canaã 1KG', 'polpa-de-morango-canaa-1kg', 'polpas-cremes', null, null, 24.99, null, '1kg', '1kg', null, false, true, 232),
  ('Polpa de Tangerina Canaã 1KG', 'polpa-de-tangerina-canaa-1kg', 'polpas-cremes', null, null, 12.99, null, '1kg', '1kg', null, false, true, 233),
  ('Polpa de Uva Canaã 1KG', 'polpa-de-uva-canaa-1kg', 'polpas-cremes', null, null, 12.99, null, '1kg', '1kg', null, false, true, 234),
  ('Ovo Caipira 12 Unidades', 'ovo-caipira-12-unidades', 'ovos', null, null, 12.99, null, 'unidade', '12 unidades', null, false, true, 235),
  ('Ovo Caipira 15 Unidades', 'ovo-caipira-15-unidades', 'ovos', null, null, 17.99, null, 'unidade', '15 unidades', null, false, true, 236),
  ('Ovos Branco Bandeja com 15 Unidades', 'ovos-branco-bandeja-com-15-unidades', 'ovos', null, null, 11.99, null, 'unidade', '15 unidades', null, false, true, 237),
  ('Ovos Vermelho Bandeja com 15 Unidades', 'ovos-vermelho-bandeja-com-15-unidades', 'ovos', null, null, 12.50, null, 'unidade', '15 unidades', null, false, true, 238),
  ('Sprite 2L Sem Açúcar', 'sprite-2l-sem-acucar', 'bebidas', null, null, 11.99, null, '2L', '2L', null, false, true, 239),
  ('Fanta Lata 350ML', 'fanta-lata-350ml', 'bebidas', null, null, 3.99, null, '350ml', '350ml', null, false, true, 240),
  ('Fanta Laranja 2L', 'fanta-laranja-2l', 'bebidas', null, null, 9.99, null, '2L', '2L', null, false, true, 241),
  ('Coca-Cola Zero 2L', 'coca-cola-zero-2l', 'bebidas', null, null, 12.99, null, '2L', '2L', null, false, true, 242),
  ('Coca-Cola Sem Açúcar 350ML', 'coca-cola-sem-acucar-350ml', 'bebidas', null, null, 4.99, null, '350ml', '350ml', null, false, true, 243),
  ('Coca-Cola Lata 350ML', 'coca-cola-lata-350ml', 'bebidas', null, null, 4.99, null, '350ml', '350ml', null, false, true, 244),
  ('Coca-Cola 2L', 'coca-cola-2l', 'bebidas', null, null, 12.99, null, '2L', '2L', null, false, true, 245),
  ('Água Mineral Sterbom 510ML', 'agua-mineral-sterbom-510ml', 'bebidas', null, null, 1.99, null, '510ml', '510ml', null, false, true, 246),
  ('Rap10 Tapioca 297G', 'rap10-tapioca-297g', 'padaria', null, null, 11.99, null, '297g', '297g', null, false, true, 247),
  ('Rap10 Original 297G', 'rap10-original-297g', 'padaria', null, null, 11.99, null, '297g', '297g', null, false, true, 248),
  ('Rap10 Integral 297G', 'rap10-integral-297g', 'padaria', null, null, 11.99, null, '297g', '297g', null, false, true, 249),
  ('Pão Plusvita Sem Açúcar 12 Grãos', 'pao-plusvita-sem-acucar-12-graos', 'padaria', null, null, 14.99, null, 'pacote', 'Pacote', null, false, true, 250),
  ('Pão Integral Plusvita 480G', 'pao-integral-plusvita-480g', 'padaria', null, null, 12.99, null, '480g', '480g', null, false, true, 251),
  ('Pão Grãos e Castanhas', 'pao-graos-e-castanhas', 'padaria', null, null, 14.99, null, 'pacote', 'Pacote', null, false, true, 252),
  ('Pão de Hambúrguer Plusvita 400G', 'pao-de-hamburguer-plusvita-400g', 'padaria', null, null, 9.99, null, '400g', '400g', null, false, true, 253),
  ('Pão de Hambúrguer Brioche Plusvita', 'pao-de-hamburguer-brioche-plusvita', 'padaria', null, null, 11.99, null, 'pacote', 'Pacote', null, false, true, 254),
  ('Pão Artesano Original', 'pao-artesano-original', 'padaria', null, null, 13.99, null, 'pacote', 'Pacote', null, false, true, 255),
  ('Pão Artesano Integral', 'pao-artesano-integral', 'padaria', null, null, 14.99, null, 'pacote', 'Pacote', null, false, true, 256),
  ('Nutrella Frutas, Grãos e Castanhas', 'nutrella-frutas-graos-e-castanhas', 'padaria', null, null, 14.99, null, 'pacote', 'Pacote', null, false, true, 257),
  ('Farinha de Rosca Plusvita 500G', 'farinha-de-rosca-plusvita-500g', 'padaria', null, null, 7.99, null, '500g', '500g', null, false, true, 258),
  ('Bolo Cocada 150G', 'bolo-cocada-150g', 'padaria', null, null, 10.99, null, '150g', '150g', null, false, true, 259),
  ('Bisnaguito Plusvita', 'bisnaguito-plusvita', 'padaria', null, null, 11.99, null, 'pacote', 'Pacote', null, false, true, 260),
  ('Bisnaguito 300G', 'bisnaguito-300g', 'padaria', null, null, 10.99, null, '300g', '300g', null, false, true, 261),
  ('Bisnaga Original Artesano 300G', 'bisnaga-original-artesano-300g', 'padaria', null, null, 11.99, null, '300g', '300g', null, false, true, 262),
  ('Bisnaga Na Chapa Artesano 300G', 'bisnaga-na-chapa-artesano-300g', 'padaria', null, null, 11.99, null, '300g', '300g', null, false, true, 263),
  ('Biscoito de Nata 160G - Vale do Açu', 'biscoito-de-nata-160g-vale-do-acu', 'padaria', null, null, 14.99, null, '160g', '160g', null, false, true, 264),
  ('Carvão Vegetal 2,5KG', 'carvao-vegetal-25kg', 'churrasco', null, null, 12.99, null, '2,5kg', '2,5kg', null, false, true, 265),
  ('Carvão Vegetal 4KG', 'carvao-vegetal-4kg', 'churrasco', null, null, 19.99, null, '4kg', '4kg', null, false, true, 266)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  image_url = coalesce(public.products.image_url, excluded.image_url),
  price = excluded.price,
  old_price = excluded.old_price,
  unit_label = excluded.unit_label,
  unit_info = excluded.unit_info,
  discount_label = excluded.discount_label,
  featured = excluded.featured,
  available = excluded.available,
  sort_order = excluded.sort_order;
